[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python3 -m ensurepip --upgrade",
    "python3 -m pip install --upgrade pip setuptools wheel",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT main:app"
