[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 main:app"
