[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 main:app"
